// <auto-generated />
using AgeOfDarknessContext.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgeOfDarknessContext.Migrations
{
    [DbContext(typeof(AgeOfDarknessDbContext))]
    [Migration("20220428200726_M3")]
    partial class M3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AgeOfDarknessContext.Models.CharacterAsset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CharacterAssets");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.KingdomAsset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("LordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KingdomAssets");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.StreetAsset", b =>
                {
                    b.Property<int>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreetId"), 1L, 1);

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("StreetId");

                    b.HasIndex("TownId");

                    b.ToTable("StreetAsset");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.TownAsset", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownId"), 1L, 1);

                    b.Property<int>("KingdomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TownId");

                    b.HasIndex("KingdomId");

                    b.ToTable("TownAssets");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.StreetAsset", b =>
                {
                    b.HasOne("AgeOfDarknessContext.Models.TownAsset", "TownAsset")
                        .WithMany("StreetAssets")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TownAsset");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.TownAsset", b =>
                {
                    b.HasOne("AgeOfDarknessContext.Models.KingdomAsset", "KingdomAsset")
                        .WithMany("TownAssets")
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KingdomAsset");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.KingdomAsset", b =>
                {
                    b.Navigation("TownAssets");
                });

            modelBuilder.Entity("AgeOfDarknessContext.Models.TownAsset", b =>
                {
                    b.Navigation("StreetAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
